### ISSUE TITLE
Parsing of `v4l::format::Description.description` is incorrect

### ISSUE THREAD

**Issue by laptou** [raymanfx/libv4l-rs#5] opened 2020-08-08 22:29 UTC
Formats with names such as `YUYV 4:2:2` appear as `"YUYV 4:2:2\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}UYV"`instead. I think this is because the parsing is not stopping at the first nul byte.

**Comment by raymanfx** [comment] 2020-08-09 10:16
I cannot reproduce this on Fedora 32 (Linux 5.7.11).
Can you provide a minimally reproducible example?
This is the code I was testing:

```rust
extern crate clap;
extern crate v4l;

use clap::{App, Arg};
use v4l::prelude::*;

fn main() {
    let matches = App::new("v4l device")
        .version("0.2")
        .author("Christopher N. Hesse <raymanfx@gmail.com>")
        .about("Video4Linux device example")
        .arg(
            Arg::with_name("device")
                .short("d")
                .long("device")
                .value_name("INDEX or PATH")
                .help("Device node path or index (default: 0)")
                .takes_value(true),
        )
        .get_matches();

    // Determine which device to use
    let mut path: String = matches
        .value_of("device")
        .unwrap_or("/dev/video0")
        .to_string();
    if path.parse::<u64>().is_ok() {
        path = format!("/dev/video{}", path);
    }
    println!("Using device: {}\n", path);

    let dev = CaptureDevice::with_path(path).expect("Failed to open device");
    let formats = dev.enum_formats().expect("Failed to enumerate formats");

    println!("Formats:");

    for format in formats {
        println!("{:#?}", format);
    }
}
```

The `{:#?}` print modifier should show any stray null character bytes.

**Comment by laptou** [comment] 2020-08-09 14:29
I mentioned in my example that I found this bug by testing a `v4l2loopback` device. This device does not have any capture formats available until something starts sending output to it, so running this example against that device actually causes a panic (which I don't think is correct; having no available capture formats is not necessarily an error).

**Comment by laptou** [comment] 2020-08-09 14:32
Here's what I get when running `v4l2-ctl`, for example:

```
~/projects/scratch 
❯ v4l2-ctl --list-devices
Dummy video device (0x0000) (platform:v4l2loopback-000):
        /dev/video2

Integrated_Webcam_HD: Integrate (usb-0000:00:14.0-12):
        /dev/video0
        /dev/video1
        /dev/media0


~/projects/scratch 
❯ v4l2-ctl --info --device /dev/video2
Driver Info:
        Driver name      : v4l2 loopback
        Card type        : Dummy video device (0x0000)
        Bus info         : platform:v4l2loopback-000
        Driver version   : 5.7.9
        Capabilities     : 0x85208003
                Video Capture
                Video Output
                Video Memory-to-Memory
                Read/Write
                Streaming
                Extended Pix Format
                Device Capabilities
        Device Caps      : 0x05208003
                Video Capture
                Video Output
                Video Memory-to-Memory
                Read/Write
                Streaming
                Extended Pix Format

~/projects/scratch 
❯ v4l2-ctl --list-formats-out --device /dev/video2
ioctl: VIDIOC_ENUM_FMT
        Type: Video Output

        [0]: 'BGR4' (32-bit BGRA/X 8-8-8-8)
        [1]: 'RGB4' (32-bit A/XRGB 8-8-8-8)
        [2]: 'BGR3' (24-bit BGR 8-8-8)
        [3]: 'RGB3' (24-bit RGB 8-8-8)
        [4]: 'RGB1' (8-bit RGB 3-3-2)
        [5]: 'R444' (16-bit A/XRGB 4-4-4-4)
        [6]: 'RGBO' (16-bit A/XRGB 1-5-5-5)
        [7]: 'RGBP' (16-bit RGB 5-6-5)
        [8]: 'RGBQ' (16-bit A/XRGB 1-5-5-5 BE)
        [9]: 'RGBR' (16-bit RGB 5-6-5 BE)
        [10]: 'BGRH' (18-bit BGRX 6-6-6-14)
        [11]: 'YUYV' (YUYV 4:2:2)
        [12]: 'UYVY' (UYVY 4:2:2)
        [13]: 'YVYU' (YVYU 4:2:2)
        [14]: 'VYUY' (VYUY 4:2:2)
        [15]: 'YYUV' (YYUV 4:2:2)
        [16]: 'YUV4' (32-bit A/XYUV 8-8-8-8)
        [17]: 'GREY' (8-bit Greyscale)
        [18]: 'Y04 ' (4-bit Greyscale)
        [19]: 'Y06 ' (6-bit Greyscale)
        [20]: 'Y10 ' (10-bit Greyscale)
        [21]: 'Y12 ' (12-bit Greyscale)
        [22]: 'Y16 ' (16-bit Greyscale)
        [23]: 'Y444' (16-bit A/XYUV 4-4-4-4)
        [24]: 'YUVO' (16-bit A/XYUV 1-5-5-5)
        [25]: 'YUVP' (16-bit YUV 5-6-5)
        [26]: 'RGGB' (8-bit Bayer RGRG/GBGB)
        [27]: 'GRBG' (8-bit Bayer GRGR/BGBG)
        [28]: 'GBRG' (8-bit Bayer GBGB/RGRG)
        [29]: 'BA81' (8-bit Bayer BGBG/GRGR)
        [30]: 'YVU9' (Planar YVU 4:1:0)
        [31]: 'YV12' (Planar YVU 4:2:0)
        [32]: 'YUV9' (Planar YUV 4:1:0)
        [33]: 'YU12' (Planar YUV 4:2:0)
        [34]: '422P' (Planar YUV 4:2:2)
        [35]: '411P' (Planar YUV 4:1:1)
        [36]: 'Y41P' (YUV 4:1:1 (Packed))
        [37]: 'NV12' (Y/CbCr 4:2:0)
        [38]: 'MJPG' (Motion-JPEG, compressed)
        [39]: 'JPEG' (JFIF JPEG, compressed)
        [40]: 'dvsd' (1394, compressed)
        [41]: 'MPEG' (MPEG-1/2/4, compressed)
        [42]: 'H264' (H.264, compressed)
        [43]: 'AVC1' (H.264 (No Start Codes), compressed)
        [44]: 'M264' (H.264 MVC, compressed)
        [45]: 'H263' (H.263, compressed)
        [46]: 'MPG1' (MPEG-1 ES, compressed)
        [47]: 'MPG2' (MPEG-2 ES, compressed)
        [48]: 'MPG4' (MPEG-4 Part 2 ES, compressed)
        [49]: 'XVID' (Xvid, compressed)
        [50]: 'VC1G' (VC-1 (SMPTE 412M Annex G), compressed)
        [51]: 'VC1L' (VC-1 (SMPTE 412M Annex L), compressed)
        [52]: 'VP80' (VP8, compressed)
        [53]: 'VP90' (VP9, compressed)
        [54]: 'HEVC' (HEVC, compressed)

```

**Comment by laptou** [comment] 2020-08-09 14:47
I can only reproduce this bug on the video format _output_ descriptions (this library does not support video output devices yet, so I had to use some lower-level code). Here's my minimal reproducible example:

```rust
extern crate clap;
extern crate v4l;
extern crate libc;

use clap::{App, Arg};
use v4l::prelude::*;
use v4l::{v4l2, v4l_sys};

fn main() {
    let matches = App::new("v4l device")
        .version("0.2")
        .author("Christopher N. Hesse <raymanfx@gmail.com>")
        .about("Video4Linux device example")
        .arg(
            Arg::with_name("device")
                .short("d")
                .long("device")
                .value_name("INDEX or PATH")
                .help("Device node path or index (default: 0)")
                .takes_value(true),
        )
        .get_matches();

    // Determine which device to use
    let mut path: String = matches
        .value_of("device")
        .unwrap_or("/dev/video0")
        .to_string();
    if path.parse::<u64>().is_ok() {
        path = format!("/dev/video{}", path);
    }
    println!("Using device: {}\n", path);

    let fd = v4l2::open(path, libc::O_RDONLY).expect("could not open device");
    println!("enumerating video output formats");

    println!("Formats:");

    let mut param: v4l_sys::v4l2_fmtdesc = unsafe { std::mem::zeroed() };
    param.type_ = v4l_sys::v4l2_buf_type_V4L2_BUF_TYPE_VIDEO_OUTPUT;

    while let Ok(()) = unsafe {
        v4l2::ioctl(
            fd,
            v4l2::vidioc::VIDIOC_ENUM_FMT,
            &mut param as *mut _ as *mut libc::c_void,
        )
    } {
        let fmt = v4l::format::Description::from(param);
        println!("\t{:#?}", fmt.description);
        println!("\t\tflags: {:#}", fmt.flags);
        println!("\t\tformat: {:#}", fmt.fourcc);
        param.index += 1;
    }
}
```

And here is the incorrect output that I get:
```
Using device: /dev/video2

enumerating video output formats
Formats:
        "YUYV 4:2:2\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}UYV"
                flags: (empty)
                format: YUYV
```

Where `/dev/video2` is `v4l2loopback` device that I am streaming `YUYV 4:2:2`-formatted video into.

**Comment by raymanfx** [comment] 2020-08-10 08:50
> I mentioned in my example that I found this bug by testing a `v4l2loopback` device. This device does not have any capture formats available until something starts sending output to it, so running this example against that device actually causes a panic (which I don't think is correct; having no available capture formats is not necessarily an error).

Can you open a separate issue for that, again with a minimal example?
What you describe is a bug, it should just yield no formats, but not panic.

**Comment by raymanfx** [comment] 2020-08-25 20:48
Closing for lack of further input.

**Closed by raymanfx** 2020-08-25 20:48 UTC
